### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by rtgtgth** [Hildaboo/PetyaBuilder#2]
Sir, we want to customize a petya virus, we can pay, if you see this message, please contact us jabber: Satan@0day.im

**Comment by epicguy492** [comment]
@rtgtgth Do not believe this person called "Hildaboo" he's a big scammer and hes from Vietnam and his Petya is skidded he cant really modify Petya, I recommend blocking and reporting him ASAP!

**Comment by epicguy492** [comment]
@rtgtgth this project https://github.com/FirstBlood12/RedPetyaOpenSSL is much better than this garbage!

**Comment by rtgtgth** [comment]
@epicguy492 Friends, thank you for your suggestion. Can the new project you recommend be compiled successfully? Can you leave your contact information for convenience?

**Comment by epicguy492** [comment]
@rtgtgth Yes, it can be compiled successfully and if you want to contact me, here is my Discord: epicguy492#0112

**Comment by Hildaboo** [comment]
I dont scam people andrej please get a life and stop spam advertising your pasted garbage on here
